### ISSUE TITLE
Extra log when publishing to Herd

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-module-resolver#112]
When publshing to Herd I get:

```
 SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
 SLF4J: Defaulting to no-operation (NOP) logger implementation
 SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

Which is reather lame, we should figure out how to disable this.

**Comment by alesj** [comment]
As the info suggests: http://www.slf4j.org/codes.html#StaticLoggerBinder

I think the issue is in Sardine's module.xml:

        <module name="org.slf4j.api" slot="1.6.1"/>

Which depends on slf4j-api module,
but this module doesn't depend on slf4j-simple, and vice-versa.

But I cannot find where we copy over those slf4j jars into dist/?
@FroMage @quintesse ^^

**Comment by alesj** [comment]
What we could do is flatten the slf4j modules into single slf4j module,
where both jars would be listed as resources.

**Comment by alesj** [comment]
Ah, it's in CMR's build.xml -- I was searching for this in Runtime ...

**Comment by alesj** [comment]
@quintesse but how does this end in Runtime's dist/ dir then?

**Comment by alesj** [comment]
Another way of fixing this would be to have the two slf4j modules depend on eachother;
hence would both have full visibility.

**Comment by quintesse** [comment]
> but how does this end in Runtime's dist/ dir then?

The runtime's `dist/` dir does not have the JARs, it only has their `module.xml` files.
This is because the runtime project deals with the dependencies necessary at runtime.
And it's the dist project that brings that all together to form the final distribution.

**Comment by quintesse** [comment]
> would be to have the two slf4j modules depend on eachother

But that wouldn't be very logical, right? What if someone wants the `api` but with a different implementation? Sure they can do it but they would have this unneeded extra dependency on `simple`.

**Comment by alesj** [comment]
>> And it's the dist project that brings that all together to form the final distribution.

Uh, how am I supposed to test this stuff then?
Or will the "dist" project properly populate Runtime's dist/ dir?

**Comment by alesj** [comment]
>> But that wouldn't be very logical, right?

Well, they have to be in the same class space,
so I don't see any other way where you would have API separate,
specially since they demand *exactly one* impl on the classpath.

**Comment by quintesse** [comment]
> Uh, how am I supposed to test this stuff then?

You test using the distribution like everybody else? ;)
The `ceylon-dist/dist` dir is the one that will contain everything

> specially since they demand exactly one impl on the classpath.

Doesn't this make it even more important that `api` does **not** have any dependencies on an implementation? Otherwise you can forget about ever using a different one. (NB: our slf4j in the distribution is not special, it's in the Herd, it should be possible that other people use it as well with different implementations if they so desire)

Although we can "cheat" a bit by using the `module.xml` files. The ones in Ceylon's system repo (the one in `ceylon-dist/dist/repo`) can be different from the ones published on the Herd. By adding a dependency on `org.slf4j.simple` to Sardine in this file https://github.com/ceylon/ceylon-runtime/blob/master/dist/repo/com/github/lookfirst/sardine/5.1/module.xml#L32

I'm not particularly fond of that solution, but it would work, right?

But what I'm wondering is how do we properly handle something like that in Ceylon?
Does something like this work perhaps:

    com.github.sardine "x.y.z"
       import org.slf4j.api "x.y.z";

    myproject
       import com.github.sardine "x.y.z";
       import org.slf4j.simple "x.y.z";

Meaning, if my project imports Sardine which imports org.slf4j.api, which needs an implementation, can I then simply import an implementation (let's say org.slf4j.simple) at the top level of my project? Will the org.slf4j.api code looking for an implementation find it?

**Comment by alesj** [comment]
>> I'm not particularly fond of that solution, but it would work, right?

No, as this is p2p classloading,
and it's the slf4j-api module that needs to see the right/needed impl.

**Comment by alesj** [comment]
>> Will the org.slf4j.api code looking for an implementation find it?

It will go look into it's own class space != top level of your project.

Own class space == module's dependencies.

**Comment by alesj** [comment]
Imo, this api2impl thing in slf4j is broken on their side.
Or I just don't see how you can tie same api resource to multiple diff impls -- by simply checking the classpath.

Such things should be dealt with service loader pattern.

**Comment by quintesse** [comment]
> Such things should be dealt with service loader pattern.

Indeed, but according to what I can find online neither `slf4j`, nor `logback` and not even `log4j` support this. It seems that only `log4j2` has this. Btw from what I read the same problem occurs with OSGi. Not sure if there's a proper solution for it there.

Anyway, I'm still surprised that it's giving a problem in *our* situation actually. Because in our loader we actually start with a flat classpath for the startup of the Ceylon toolchain itself... which includes Sardine and org.slf4j.api and org.slf4j.simple! So why on earth are we having this problem?

**Comment by alesj** [comment]
>> So why on earth are we having this problem?

I very much doubt this is coming from a flat classpath.
If Runtime is involed, it's not flat.

**Comment by quintesse** [comment]
Well first of all I'm not so sure the runtime is involved at all, Stef talks about "publishing" which is probable using the compiler to directly compile to the Herd.

Second, even if the runtime were involved all these JARs are made part of the runtime's classpath, so I think they fall outside of the entire module system. (It might be different if a module running inside the runtime were to try and use Sardine, but that's not the case here)

**Comment by alesj** [comment]
>> Second, even if the runtime were involved all these JARs are made part of the runtime's classpath, so I think they fall outside of the entire module system.

Afaik, CMR inside Runtime runs as modules.

**Comment by quintesse** [comment]
But which CMR "inside Runtime"? We don't have any example of that, we're not using CMR "inside" anywhere (right now). Like I said I would expect this problem if someone would be doing that, but right now our compiler is not a module, none of Ceylon is. We *expose* them as modules as well, but we don't use them as such ourselves.

**Comment by alesj** [comment]
A?
When Runtime uses CMR, it's a module.
Or not anymore?
As it used to be.

**Comment by quintesse** [comment]
@FroMage could you provide an exact example of how to reproduce this? I thought I knew but I'm actually not able to reproduce this with anything that I think means "When publishing to Herd"...
(the only place I could reproduce this was actually configured wrong, when I fixed the config the problem went away)

**Comment by FroMage** [comment]
Well, usually just create a new upload on Herd and then publish to it with `ceylon compile --out ... --user ... --pass ... my.module` or `ceylon copy`. Perhaps this is limited to the same incantation in ant though?

**Comment by quintesse** [comment]
Ah this was with Ant? OK I'll try that and see what happens.

**Comment by quintesse** [comment]
@FroMage I just tried this with "ant herd-publish" in the SDK and I don't get any log message from SLF4J, so right now I'm unable to reproduce this.

**Comment by FroMage** [comment]
OK, well if you can't reproduce it from the CLI or ant then it's probably been fixed.
