### ISSUE TITLE
Overrides.xml not applied on jars for which no dependency resolver returned a result

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-module-resolver#120]
For a simple Jar with no descriptor at all, no dependency resolver suceeds in return a ModuleInfo.
In this case, the Overrides rules are not applied.
It's a pity, because (in case of flat repo for example), this would give the opportunity to add dependencies.

**Comment by FroMage** [comment]
Had to revert your change because it breaks the contract of that method and the `CeylonToolProvider` tests. If you give me more info about the feature, and a way to test it, I can help. What we do for modules which have no module descriptor in a flat classpath is to add a module descriptor for them rather than an overrides, in another flat repo. Would that help for your use-case?
